apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openunison-login
  namespace: argocd
spec:
  destination:
    namespace: openunison
    server: 'https://kubernetes.default.svc'
  ignoreDifferences:
  - group: admissionregistration.k8s.io
    jsonPointers:
    - /webhooks/0/clientConfig/caBundle
    - /webhooks/1/clientConfig/caBundle
    - /webhooks/2/clientConfig/caBundle
    - /webhooks/3/clientConfig/caBundle
    - /webhooks/4/clientConfig/caBundle
    kind: ValidatingWebhookConfiguration
  project: default
  sources:
  - chart: openunison-operator
    helm:
      releaseName: openunison
      valueFiles:
      - $values/userauth/values.yaml
    repoURL: https://nexus.tremolo.io/repository/helm
    targetRevision: XXXX

  - chart: orchestra
    helm:
      releaseName: orchestra
      valueFiles:
      - $values/userauth/values.yaml
    repoURL: https://nexus.tremolo.io/repository/helm
    targetRevision: 

  - chart: orchestra-login-portal
    helm:
      releaseName: orchestra-login-portal
      valueFiles:
      - $values/userauth/values.yaml
    repoURL: https://nexus.tremolo.io/repository/helm
    targetRevision: XXXX

  - repoURL: https://github.com/TremoloSecurityDemos/openunison-argocd.git
    path: userauth
  - ref: values
    repoURL: https://github.com/TremoloSecurityDemos/openunison-argocd.git
  syncPolicy:
    syncOptions:
    - RespectIgnoreDifferences=true