name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2

      - name: generate templates
        run: |-
          OPENUNISON_OPERATOR_VERSION=$(curl https://nexus.tremolo.io/repository/helm/charts.json  2>/dev/null | jq -r '.[] | select(.name == "openunison-operator") | .version')
          OPENUNISON_ORCHESTRA_VERSION=$(curl https://nexus.tremolo.io/repository/helm/charts.json  2>/dev/null | jq -r '.[] | select(.name == "orchestra") | .version')
          OPENUNISON_ORCHESTRA_LOGIN_PORTAL_VERSION=$(curl https://nexus.tremolo.io/repository/helm/charts.json  2>/dev/null | jq -r '.[] | select(.name == "orchestra-login-portal") | .version')

          cat docs/assets/yaml/argocd-application-template.yaml | sed s/OPENUNISON_OPERATOR_VERSION/$OPENUNISON_OPERATOR_VERSION/g | sed s/OPENUNISON_ORCHESTRA_VERSION/$OPENUNISON_ORCHESTRA_VERSION/g | sed s/OPENUNISON_ORCHESTRA_LOGIN_PORTAL_VERSION/$OPENUNISON_ORCHESTRA_LOGIN_PORTAL_VERSION/g > docs/assets/yaml/argocd-application.yaml

        
      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        # Or use mhausenblas/mkdocs-deploy-gh-pages@nomaterial to build without the mkdocs-material theme
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          EXTRA_PACKAGES: build-base
          REQUIREMENTS: .mkdocs-req/requirements.txt
          # GITHUB_DOMAIN: github.myenterprise.com